name: ci

on:
  pull_request:
  push:
    branches:
      - new
jobs:
  publish:
     runs-on: ubuntu-latest 
     steps:
            - uses: actions/checkout@v2
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v1
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1
            - name: Login do docker.io
              env: 
                DOCKER_USER: ${{ secrets.DOCKER_USER }}
                DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
              run: |
                docker login -u abhay900 -p abhay12
            - name: build-push-image                  
              id: docker_build 
              uses: docker/build-push-action@v2
              with:
                context: .
                file: ./etc/proto/Dockerfile
                platforms: linux/amd64,linux/arm64
                push: true
                tags: abhay900/pachyd:latest
